### ISSUE TITLE
Error: An API access token is required to use Mapbox GL

### ISSUE THREAD

**Issue by wensonsmith** [CaviarChen/fog-machine#34]
Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes

Should i register Mapbox and get the token by myself  or just set a default token in the code ?

some explanation in docs will be better

**Comment by tavimori** [comment]
Thanks for your feedback. 

Yes, you need to register a free Mapbox account to obtain your key. Then save the key to `.env.local` according to `.env.local.example` in the repository's root directory.

We'll update the readme accordingly.
