### ISSUE TITLE
Add option to export data to an open file format like .gpx

### ISSUE THREAD

**Issue by quietoutbursts** [CaviarChen/fog-machine#41]

**Comment by tavimori** [comment]
The internal data format of _Fog of World_ is like a black-white picture indicating where you've been and there is no time ordering between the pixels.
Considering GPX is a format for storing waypoints (with ordering), it is a fundamentally different format from FoW's. 
In short, you may consider FoW as a bitmap image, while GPX is a vector image. Therefore GPX to FoW will only be a one-way transform. 
If you still prefer GPX, I'd recommend using other tools (without FoW support).

If you have any other suggestions, please reopen the ticket.

**Comment by CaviarChen** [comment]
I feel like if the use case is getting gpx data out of existing fow data, that's still something worth considering (again one shouldn't use fog of world to record gpx data in the first place).
It's possible to guess and reconsturct a close enough vector graph from a bitmap image.
