### ISSUE TITLE
请问如何增加定位点？

### ISSUE THREAD

**Issue by GeorgeGalway** [CaviarChen/fog-machine#45]
我能手工绘制我走过的路线吗？

**Comment by tavimori** [comment]
正在开发，目前打算提供画直线段和任意绘制两个方案。

**Comment by GeorgeGalway** [comment]
或者提供导入坐标点也不错，谢谢回复，一直关注，已Star

**Comment by tavimori** [comment]
> 或者提供导入坐标点也不错，谢谢回复，一直关注，已Star

现有的迷雾APP有导入gpx功能，该功能不能满足需求么？

**Comment by GeorgeGalway** [comment]
> 

嗯，我就是觉得那个有点麻烦，还是提供任意绘制比较好，谢谢

**Comment by CaviarChen** [comment]
已在 #70 中完成
